name: Deploy to Heroku

on:
  push:
    branches:
      - main
      - master
      - new-deployment-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Heroku Container Registry
      uses: docker/login-action@v1
      with:
        registry: registry.heroku.com
        username: _
        password: ${{ secrets.HEROKU_API_KEY }}

    - name: Build and push Docker image to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        docker build -t registry.heroku.com/quiet-meadow-75538/web .
        docker push registry.heroku.com/quiet-meadow-75538/web

    - name: Release Docker image on Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:release web --app quiet-meadow-75538
